name: Generate Mikrotik RSC

on:
  push:
    branches: [ main ]
    paths:
      - 'rule.list'
  schedule:
    - cron: '0 0 * * 0'  # 每周日00:00执行
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Generate RSC file
        run: python .github/scripts/generate_rsc.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add asn.rsc
          git diff --staged --quiet || git commit -m "Update asn.rsc"
          git push