name: Generate Mikrotik RSC

on:
  push:
    branches: [ main ]
    paths:
      - 'rule.list'
  schedule:
    - cron: '0 0 * * 0'  # 每周日00:00执行
  workflow_dispatch:  # 允许手动触发

# 添加这个权限块
permissions:
  contents: write  # 这给予工作流写入仓库内容的权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Generate RSC file
        run: python .github/scripts/generate_rsc.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          if [ -f asn.rsc ]; then
            git add asn.rsc
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update asn.rsc"
              # 使用 GITHUB_TOKEN 推送
              git push
            fi
          else
            echo "Warning: asn.rsc file was not created"
            exit 1
          fi